### ISSUE TITLE
fehlende Informationen in der Informationsleiste

### ISSUE THREAD

**Issue by eriu** [hopglass/hopglass#1]
In der aktuellen Version vom Hopglass https://github.com/plumpudding/hopglass/commit/1bcd2b797dc1ac2dc804084f6934a33112e942f6
fehlen links in der Bar nicht die Anzahl der Knoten und der Gateways, obwohl diese mit der alias.json zugeordnet werden und auch in der Statistik richtig erkannt werden

* getestet mit hopglass-server v0.1.1

Beispiel:
**magdeburg**
252 Knoten (219 online, 6 neu, 34 verschwunden), NaN Clients, 0 Gateways
https://map.md.freifunk.net/
https://map.md.freifunk.net/stats

**eulenfunk**
1310 Knoten (973 online, 148 neu, 340 verschwunden), 2527 Clients, 0 Gateways
https://map.eulenfunk.de/
https://map.eulenfunk.de/stats/

**Comment by plumpudding** [comment]
Ein Gateway-Flag sollte nur in Spezialfällen (L3-Netzwerke) in der Aliases.json eingetragen. Es ist nämlich ein Wert der sich verändern kann. In BATMAN-Netzen ist ein "Gateway" z.B. ein flag, das vom Admin mal eben auf "server" gesetzt wird. Deshalb sollten die Gateways dynamisch ermittelt werden. Das ist in Arbeit.

**Comment by plumpudding** [comment]
Ich habe da was eingebaut. Probier es mal mit dem neuesten HopGlass-Web.

**Comment by eriu** [comment]
Ich hab jetzt den web Teil auf https://github.com/plumpudding/hopglass/commit/2da97bca161551d130e46d27245b4a4dd1afc77d aktualisiert. Jedoch werden die Anzahl der Clients bei mir noch nicht angezeigt.

Soll Ich aus der aliases.json nur die batman interfaces entfernen? 

aktuelle aliases.json:

```
  {
    "d2f429996861": {
      "firstseen": "2016-04-07T17:49:18.252Z",
      "nodeinfo": {
        "node_id": "d2f429996861",
        "owner": {
          "contact": "kontakt@md.freifunk.net"
        },
        "network": {
          "mac": "d2:f4:29:99:68:61",
          "mesh_interfaces": [
            "d2:f4:29:99:68:61"
          ],
          "mesh": {
            "bat0": {
              "interfaces": {
                "tunnel": [
                  "d2:f4:29:99:68:61"
                ]
              }
            }
          }
        },
        "hostname": "gw1"
     },
      "neighbours": {
        "batadv": {
          "d2:f4:29:99:68:61": {}
        }
      }
    }        
    "be981f07ffa3": {
      "firstseen": "2016-04-07T17:49:18.252Z",
      "nodeinfo": {
        "node_id": "be981f07ffa3",
        "owner": {
          "contact": "kontakt@md.freifunk.net"
        },
        "network": {
          "mac": "be:98:1f:07:ff:a3",
          "mesh_interfaces": [
            "be:98:1f:07:ff:a3"
          ],
          "mesh": {
            "bat0": {
              "interfaces": {
                "tunnel": [
                  "be:98:1f:07:ff:a3"
                ]
              }
            }
          }
        },
        "hostname": "gw2"
     },
      "neighbours": {
        "batadv": {
          "be:98:1f:07:ff:a3": {}
        }
      }
    }
  }  
```

**Comment by plumpudding** [comment]
Dann bitte such den HG Server updaten..

**Comment by eriu** [comment]
Hi,

mit hopglass-server https://github.com/hopglass/hopglass-server/commit/fd7cedfc2777324b240383f0c3347567faa3dd83
und hopglass https://github.com/plumpudding/hopglass/commit/2da97bca161551d130e46d27245b4a4dd1afc77d

gibt es bei mir auch keine Verbesserung, die Clients und GW fehlen immernoch in der Übersicht

**Comment by plumpudding** [comment]
Link zur Karte?

**Comment by eriu** [comment]
map.md.freifunk.net

**Comment by plumpudding** [comment]
That is not plumpudding/hopglass@2da97bc running on that map..

**Comment by eriu** [comment]
danke jetzt gehts :) https://map.md.freifunk.net/
