### ISSUE TITLE
Airtime always displayed as NaN

### ISSUE THREAD

**Issue by TobleMiner** [hopglass/hopglass#100]
We at Freifunk Kiel have just updated our firmware release to include airtime data. Unfortunately Hopglass displays Nan % airtime usage on the airtime bars in the node infobox.

I think the data prepared by hopglass-server is not parsed correctly by hopglass. It seems like hopglass expects a simple floating point value where hopglass-server actually puts an object with a lot more detailed airtime usage information.

**Comment by TobleMiner** [comment]
I've just created a PR #101 . Hope it will get merged. There has not really been terribly much activity here lately, has it?

**Comment by petabyteboy** [comment]
Fixed
