### ISSUE TITLE
Nodes shwon as "new" when name changed

### ISSUE THREAD

**Issue by karlbeecken** [hopglass/hopglass#107]
Whenever I change a name of a node in the berlin hopglass setup, the node is always shown as a new device. Would it be possible to generate a UUID per device so that you can see, that the node isn't new?

**Comment by petabyteboy** [comment]
Hi, do you have an example for this? The `firstseen` property should be bound to the node's id, which is derived from its MAC address.

**Comment by karlbeecken** [comment]
I have several nodes here in Berlin which are all ~9 months part of the network, they all were two weeks or so offline, now they are listed under the new nodes category, the time "part of the network" is also too small.

**Comment by petabyteboy** [comment]
This is a problem specific to the owm2ffmap backend used by Freifunk Berlin. Please report the issue [here](https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net).
