### ISSUE TITLE
[request] vector map support

### ISSUE THREAD

**Issue by Moorviper** [hopglass/hopglass#72]
currently hopglass/meshviewer can only use picture based tiles.

A improvement would be if we could use vector maps
A demo as a performance showcase:
http://fffd.meshviewer.net
(performs much better on weaker internet connections)

**Comment by plumpudding** [comment]
I guess we'd have to update leaflet for this? @xf- has updated leaflet in his fork, maybe we can cherry-pick this (probably a bit more work than just cherry-picking it). 

Performance when moving the map on http://fffd.meshviewer.net is very poor even on a strong PC. It doesn't seem ready.

**Comment by plumpudding** [comment]
https://petabyteboy.de/daten/hg-vector-map.png

**Comment by Moorviper** [comment]
i used safari and vivaldi for testing on a macbook ret 2015 16GB +radeon
eher was no performance problem iPhoneSE  works well, too.

On the page i use leaflet 1.0 but i think it was necessary for using the node separation plugin for leaflet.
I can check this out ...

**Comment by xf-** [comment]
@plumpudding i only tested stuff. Had some issues with leftlet v1 RC. Still interesting, but Demo with Map performance with vector was worse (fffd has no http2).
