### ISSUE TITLE
Wifi/Lan-Clients separated in stats and color

### ISSUE THREAD

**Issue by Adorfer** [hopglass/hopglass#79]
Besteht die Möglichkeit, anhand der vom Knoten übermittelten Daten die WiFi-Clients farblich (und in der Tabelle in Zahlen) anders auszuzeichnen als die Wire-Clients am LANport?

Übertragen werden die Infos, es müsste nur visualisiert werden.
Auch für die Verteilung "5GHz" vs "2.4GHz-Clients" wäre es interessant.

**Comment by plumpudding** [comment]
Die Möglichkeit besteht, die Daten kommen am HG Server an, werden noch nicht an den HG Client weitergegeben.

**Comment by RalfJung** [comment]
Ich glaube das ist inzwischen implementiert? Bei uns haben Clients jetzt zumindets verschiedene Farben. :)

**Comment by anoymouserver** [comment]
Implementiert mit 727f0e5dd852e23fb7bf629d81eee233061713b7. Danke für den Hinweis.
