### ISSUE TITLE
Link/Graph für Meshlinks von Hoplass>Grafana invertiert

### ISSUE THREAD

**Issue by Adorfer** [hopglass/hopglass#83]
Der Graph und Link für Meshlinks ist leider hinsichtlich source/dst vertauscht. 

Das fällt insbesondere bei unidirektionalen Links auf
siehe  z.B. 
https://map.ffdus.de/#!v:m;l:68725116004c-98ded04bb108

![grafik](https://cloud.githubusercontent.com/assets/10302493/22191010/8b76586e-e127-11e6-898b-24d4b67d18db.png)

**Comment by Adorfer** [comment]
p.S. manuell "umgedreht" gibt's dann Daten: 

![grafik](https://cloud.githubusercontent.com/assets/10302493/22191040/c2517846-e127-11e6-9f99-2519bef441bc.png)

**Comment by plumpudding** [comment]
Konfigurationsproblem
