### ISSUE TITLE
[BUG] (mit fix) schlechte Performance in der forcegraph.js

### ISSUE THREAD

**Issue by Moorviper** [hopglass/hopglass#85]
Hi Milan, 
Aktuell werden in der forcegraph die client bei jeder Zoomstufe gezeichnet.

Fix:
https://forum.freifunk.net/t/hopglass-development-thread/10984/155

(Mein lokales Git-Repo ist grade vollig unbrauchbar / sonst hätte ich nen pullrequest gemacht / ist ja nur eine Zeile ;-) )

**Comment by plumpudding** [comment]
https://github.com/hopglass/hopglass/commit/1a6a4329b5417991d9ba0019065e0e5c9dcb1648
