### ISSUE TITLE
Routerpics for WR84xxx with antennas

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass#88]
I think, we should use the old images for those that still have antennas:

https://github.com/Moorviper/Freifunk-Router-Anleitungen/blob/d756e22f1e08bd191c39e874d3bf476abff50e27/tp-link-tl-wr841n-nd-v10/front.jpg

<img src="https://nord.freifunk.net/images/models/tp-link-tl-wr841n-nd_100x60.png">

**Comment by Moorviper** [comment]
the problem with this picture is that the drawing was bad
I cannot fill the body because of some bad curves i will fix this in april

**Comment by Moorviper** [comment]
https://github.com/Moorviper/Freifunk-Router-Anleitungen/commit/e2f5221bd9462a28d2227694050149960b9a05e2

I upload the rest this evening / they are already drawn but i have to copy them in the right folder / and for the routerpics in meshviewer/hopglass i have to hash them.

**Comment by Moorviper** [comment]
done
