### ISSUE TITLE
Add option to anonymize statistics on some nodes

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass#94]
For privacy reasons it is important for some nodes, that the statistics are not so openly visible like at the moment. For example you can easily track when someone is at home and using the internet on nodes that are lonely in one place on the countryside, or such.

We have to add a configurable list of nodes, that wants to be anonymized.

Just hiding the statistics and number of connected clients could make observers suspicious and curieóus about this node, so those node should get their shown number of clients and statistics randomly changed, so a map visitor doesn't get suspicious.

This would be one part of a solution for  https://github.com/freifunk-gluon/gluon/issues/1127

**Comment by mar-v-in** [comment]
@rubo77 as long as the node reports this data to the network, everyone on the network can gather it. So, just for the record, what you are suggesting is not anonymization, but obfuscation (which isn't necessarily a bad thing).

**Comment by rubo77** [comment]
Yes. We should hide those data on the usually public map if someone wants it.

Should be easily to be implemented

**Comment by plumpudding** [comment]
This has to be implemented on the node.

**Comment by rubo77** [comment]
Please reopen.

This cannot be implemented on the nodes, because the link stats are vital to batman.

We should implement this here to improve some privacy where wanted

**Comment by mar-v-in** [comment]
@rubo77: Batman data is not used by hopglass to create stats. The actual stats are reported through respondd on the nodes whose only purpose is to provide stats. If you want to remove certain data from stats, you should do so by modifying the data this daemon reports to hopglass.
