### ISSUE TITLE
Add information about the work progress

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass#98]
I try to merge this project back into the original project: https://github.com/ffnord/meshviewer

It is not clear, how you work in this project. Please add informations to the README:

- How are the different branches used
- how do you prepare releases
- mark stable commits as tags with versions

please use the original tags from https://github.com/ffnord/meshviewer/tags appended with "-hopglass", so the next stable version should be tagged as v5-hopglass

the other main branch will also be added to the original project, see https://github.com/ffrgb/meshviewer/issues/188

**Comment by plumpudding** [comment]
look here: https://github.com/hopglass/meshviewer
