### ISSUE TITLE
vendor/es6-shim/es6-shim.js fehlt

### ISSUE THREAD

**Issue by Tarnatos** [hopglass/hopglass#99]
Wärend des debuggens eines anderen Fehlers fiel mir auf, dass Hopglass versucht die Datei vendor/es6-shim/es6-shim.js zu laden.

Diese fehlt.

Es gibt sie hier:
https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js

**Comment by petabyteboy** [comment]
Removed, since all browsers support es6 by now
